# Site settings
title: Emma Loos
email: emmasponsorloop@outlook.com
instagram_username: samenvooremma
author: Mirelle en Edwin Loos
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.emmaloos.nl" # the base hostname & protocol for your site, e.g. http://example.com
contacturl: "mailto:emmasponsorloop@outlook.com"
doneerurl: "https://betaalverzoek.rabobank.nl/betaalverzoek/?id=XqAcgJQ2RC6XodDJkiR0Qg"
# inschrijfurl: "https://docs.google.com/forms/d/e/1FAIpQLSeGxkPpnSOvD9rU0x2rxgNJKMVzKEF8adS7lfRtxbjvlm_9GA/viewform?usp=dialog"
nieuwsbriefurl: "https://docs.google.com/forms/d/e/1FAIpQLSenK6r9ADBG_ysQ2fu75xHyYXu5LPucJTVSSPrct4lNasmZeA/viewform?usp=dialog"
veilingurl: "https://emmaloos.itsam.nl"

sponsors:
  - name: "Foley Tales"
    url: "https://foleytales.com"
    image: "/img/sponsors/foley-tales.png"
  - name: "Elisa Jo Studios"
    url: "https://elisajo.com/"
    image: "/img/sponsors/elisa-jo-studios.png"
  - name: "Bas Balloon"
    url: "https://www.basballoon.nl/"
    image: "/img/sponsors/basballoon.jpg"
  - name: "BJD Finance"
    url: "https://www.bjdfinance.nl/"
    image: "/img/sponsors/bjd-finance.png"
  - name: "Dance First"
    url: "https://www.dancefirst.nl/"
    image: "/img/sponsors/dance-first.jpg"
  - name: "Feest en Verhuur Alkmaar"
    url: "https://www.feestenverhuuralkmaar.nl/"
    image: "/img/sponsors/feest-en-verhuur.jpg"
  - name: "Fietsvakman Paul Harder"
    url: "https://www.paulharder.nl/"
    image: "/img/sponsors/fietsvakman-paul-harder.jpg"
  - name: "Boedelzorg Steenhof"
    url: "https://boedelzorg-steenhof.nl"
    image: "/img/sponsors/handelsonderneming-steenhof.png"
  - name: "Oostwouder Aannemers"
    url: "https://oostwouder.info/"
    image: "/img/sponsors/oostwouder-aannemers.jpg"
  - name: "Partners in Verloskunde"
    url: "https://www.partnersinverloskunde.nl/"
    image: "/img/sponsors/partners-in-verloskunde.png"
  - name: "Alkmaarse Poort"
    url: "https://www.alkmaarsepoort.nl/"
    image: "/img/sponsors/alkmaarse-poort.jpg"
  - name: "Coast Riders Chapter Alkmaar"
    url: "https://www.coastriderschapter.nl/"
    image: "/img/sponsors/coast-riders-alkmaar.png"
  - name: "Voetbalvereniging Kolping Boys"
    url: "https://www.kolpingboys.nl/"
    image: "/img/sponsors/kolping-boys.png"
  - name: "Sportinstituut Tom van der Kolk"
    url: "https://tomvanderkolk.nl"
    image: "/img/sponsors/tom-van-der-kolk.jpg"


# Build settings
# theme: jekyll-theme-clean-blog # minima
# plugins:
#   - jekyll-feed

